spring.application.name=learn_english_app
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/english_app_database?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.key.pub=classpath:english_app.pub
jwt.key.pri=classpath:english_app.pri
